name: "GoSec"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run GoSec to check for vulnerabilities
      uses: ynniss/golang-security-action@master
      with:
        CODE_PATH: "."